<a href="https://colab.research.google.com/github/PanavShah1/DAV_assignment/blob/main/DAV_Q3_Q4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## DAV Assignment Q3 and Q4
After extensive research, suppose you decided to enter the Indian Market with
your existing products (P, Q, R, S and T).
Your team has determined that the behavior of the new market in India closely
mirrors that of your existing market. In your current market, the sales team
categorizes all customers into four segments (A, B, C, D). They then tailor their
outreach and communication strategies to each specific segment. This
approach has proven to be highly effective for them.

They plan to use the same strategy for the Indian markets and have identified
about 2500 new potential trial customers. For this they have an existing
database of about 8000 customers which they have already classified.

### Q3: Implement methods to assist your team in identifying and predicting the appropriate group (A, B, C, or D) for each customer in the test data.

In [ ]:
# Import libraries
import requests
from pathlib import Path
import zipfile
import os


request = requests.get("https://github.com/PanavShah1/DAV_assignment/blob/main/Consumer_Dataset.csv?raw=true")
with open("Consumer_Dataset.csv", "wb") as f:
  f.write(request.content)
  print("csv file downloaded")

request = requests.get("https://github.com/PanavShah1/DAV_assignment/blob/main/Consumer%20Test%20Dataset.csv?raw=true")
with open("Consumer_Test_Dataset.csv", "wb") as f:
  f.write(request.content)
  print("csv file downloaded")


csv file downloaded
csv file downloaded


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("Consumer_Dataset.csv")
df.head(5)



Unnamed: 0  Gender  Age Ever_Married  Family_Size     Profession Graduated  \
0           0    Male   22           No          4.0     Healthcare        No   
1           1  Female   38          Yes          3.0       Engineer       Yes   
2           2  Female   67          Yes          1.0       Engineer       Yes   
3           3    Male   67          Yes          2.0         Lawyer       Yes   
4           4  Female   40          Yes          6.0  Entertainment       Yes   

   Work_Experience Energy_Consumption Preferred_Renewable Group  
0              1.0                Low               Hydro     D  
1              NaN            Average               Hydro     A  
2              1.0                Low               Solar     B  
3              0.0               High               Solar     B  
4              NaN               High               Solar     A

In [ ]:
len(df)

8068

## Get the dataset ready

In [ ]:
professions = df['Profession'].unique()
professions

array(['Healthcare', 'Engineer', 'Lawyer', 'Entertainment', 'Artist',
       'Executive', 'Doctor', 'Homemaker', 'Marketing', nan], dtype=object)

In [ ]:
renewable = df['Preferred_Renewable'].unique()
renewable

array(['Hydro', 'Solar', 'Not Interested', 'Wind', 'Tidal', 'Biomass',
       nan, 'Geothermal'], dtype=object)

In [ ]:
avg_work_experience = df['Work_Experience'].mean()
avg_work_experience

2.641663213150988

In [ ]:
avg_family_size = df['Family_Size'].mean()
avg_family_size

2.85012285012285

In [ ]:
df = df.replace(to_replace="Male", value=0)
df = df.replace(to_replace="Female", value=1)
df = df.replace(to_replace="Yes", value=1)
df = df.replace(to_replace="No", value=0)
df['Work_Experience'] = df['Work_Experience'].fillna(avg_work_experience)
df = df.replace(to_replace="Low", value=0)
df = df.replace(to_replace="Average", value=1)
df = df.replace(to_replace="High", value=2)
df['Family_Size'] = df['Family_Size'].fillna(avg_family_size)

df = df.replace(to_replace="A", value=0)
df = df.replace(to_replace="B", value=1)
df = df.replace(to_replace="C", value=2)
df = df.replace(to_replace="D", value=3)
df

Unnamed: 0  Gender  Age  Ever_Married  Family_Size     Profession  \
0              0       0   22           0.0          4.0     Healthcare   
1              1       1   38           1.0          3.0       Engineer   
2              2       1   67           1.0          1.0       Engineer   
3              3       0   67           1.0          2.0         Lawyer   
4              4       1   40           1.0          6.0  Entertainment   
...          ...     ...  ...           ...          ...            ...   
8063        8063       0   22           0.0          7.0            NaN   
8064        8064       0   35           0.0          4.0      Executive   
8065        8065       1   33           0.0          1.0     Healthcare   
8066        8066       1   27           0.0          4.0     Healthcare   
8067        8067       0   37           1.0          3.0      Executive   

      Graduated  Work_Experience  Energy_Consumption Preferred_Renewable  \
0           0.0         1.000000                   0               Hydro   
1           1.0         2.641663                   1               Hydro   
2           1.0         1.000000                   0               Solar   
3           1.0         0.000000                   2               Solar   
4           1.0         2.641663                   2               Solar   
...         ...              ...                 ...                 ...   
8063        0.0         0.000000                   0               Tidal   
8064        0.0         3.000000                   0               Hydro   
8065        1.0         1.000000                   0               Solar   
8066        1.0         1.000000                   0               Solar   
8067        1.0         0.000000                   1               Hydro   

      Group  
0         3  
1         0  
2         1  
3         1  
4         0  
...     ...  
8063      3  
8064      3  
8065      3  
8066      1  
8067      1  

[8068 rows x 11 columns]

In [ ]:
for i, source in enumerate(professions):
  df['Profession'][df['Profession'] == source] = i
avg_profession = df['Profession'].mean()
df['Profession'] = df['Profession'].fillna(avg_profession)
avg_profession

<ipython-input-10-2b2318068495>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profession'][df['Profession'] == source] = i
<ipython-input-10-2b2318068495>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profession'][df['Profession'] == source] = i
<ipython-input-10-2b2318068495>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profession'][df['Profession'] == source] = i
<ipython-input-10-2b2318068495>:2: SettingWithCop

3.2775679758308156

In [ ]:
avg_married = df['Ever_Married'].mean()
df['Ever_Married'] = df['Ever_Married'].fillna(avg_married)
avg_married

0.5856458123107972

In [ ]:
for i, source in enumerate(renewable):
  df['Preferred_Renewable'][df['Preferred_Renewable'] == source] = i
avg_preferred_renewable = df['Preferred_Renewable'].mean()
df['Preferred_Renewable'] = df['Preferred_Renewable'].fillna(avg_preferred_renewable)
avg_preferred_renewable

<ipython-input-12-cd5c1d51057a>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Preferred_Renewable'][df['Preferred_Renewable'] == source] = i
<ipython-input-12-cd5c1d51057a>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Preferred_Renewable'][df['Preferred_Renewable'] == source] = i
<ipython-input-12-cd5c1d51057a>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Preferred_Renewable'][df['Preferred_Renewable'] == source]

1.4197947947947949

In [ ]:
avg_graduated = df['Graduated'].mean()
df['Graduated'] = df['Graduated'].fillna(avg_graduated)
avg_graduated

0.6217772215269086

In [ ]:
df.isnull().values.any()


False

In [ ]:
df = df.drop('Unnamed: 0', axis=1)
df

Gender  Age  Ever_Married  Family_Size  Profession  Graduated  \
0          0   22           0.0          4.0    0.000000        0.0   
1          1   38           1.0          3.0    1.000000        1.0   
2          1   67           1.0          1.0    1.000000        1.0   
3          0   67           1.0          2.0    2.000000        1.0   
4          1   40           1.0          6.0    3.000000        1.0   
...      ...  ...           ...          ...         ...        ...   
8063       0   22           0.0          7.0    3.277568        0.0   
8064       0   35           0.0          4.0    5.000000        0.0   
8065       1   33           0.0          1.0    0.000000        1.0   
8066       1   27           0.0          4.0    0.000000        1.0   
8067       0   37           1.0          3.0    5.000000        1.0   

      Work_Experience  Energy_Consumption  Preferred_Renewable  Group  
0            1.000000                   0                  0.0      3  
1            2.641663                   1                  0.0      0  
2            1.000000                   0                  1.0      1  
3            0.000000                   2                  1.0      1  
4            2.641663                   2                  1.0      0  
...               ...                 ...                  ...    ...  
8063         0.000000                   0                  4.0      3  
8064         3.000000                   0                  0.0      3  
8065         1.000000                   0                  1.0      3  
8066         1.000000                   0                  1.0      1  
8067         0.000000                   1                  0.0      1  

[8068 rows x 10 columns]

In [ ]:
data = df.to_numpy()
data

array([[ 0., 22.,  0., ...,  0.,  0.,  3.],
       [ 1., 38.,  1., ...,  1.,  0.,  0.],
       [ 1., 67.,  1., ...,  0.,  1.,  1.],
       ...,
       [ 1., 33.,  0., ...,  0.,  1.,  3.],
       [ 1., 27.,  0., ...,  0.,  1.,  1.],
       [ 0., 37.,  1., ...,  1.,  0.,  1.]])

In [ ]:
data.shape

(8068, 10)

In [ ]:
X = data[:, 0:9]
y = data[:, 9]
X.shape, y.shape

((8068, 9), (8068,))

In [ ]:
X[0], y[0]

(array([ 0., 22.,  0.,  4.,  0.,  0.,  1.,  0.,  0.]), 3.0)

In [ ]:
import torch
from torch import nn

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
X = torch.from_numpy(X)
y = torch.from_numpy(y)
X.shape, y.shape

(torch.Size([8068, 9]), torch.Size([8068]))

In [ ]:
X = X.type(torch.float32)
y = y.type(torch.long)
X.dtype, y.dtype

(torch.float32, torch.int64)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

(torch.Size([7261, 9]),
 torch.Size([807, 9]),
 torch.Size([7261]),
 torch.Size([807]))

In [ ]:
from torch.utils.data import Dataset

class ConsumerDataset(Dataset):
  def __init__(self, X, y):
    self.X = X
    self.y = y

  def __len__(self):
    return len(self.X)

  def __getitem__(self, idx):
    return self.X[idx], self.y[idx]

train_dataset = ConsumerDataset(X_train, y_train)
test_dataset = ConsumerDataset(X_test, y_test)
train_dataset, test_dataset

(<__main__.ConsumerDataset at 0x7daf1091f610>,
 <__main__.ConsumerDataset at 0x7daf1091f640>)

In [ ]:
train_dataset[:5]

(tensor([[ 1.0000, 30.0000,  0.0000,  1.0000,  1.0000,  0.0000, 11.0000,  0.0000,
           0.0000],
         [ 0.0000, 40.0000,  1.0000,  2.0000,  3.0000,  1.0000,  1.0000,  1.0000,
           1.4198],
         [ 0.0000, 73.0000,  1.0000,  4.0000,  3.0000,  1.0000,  1.0000,  2.0000,
           1.0000],
         [ 0.0000, 28.0000,  0.0000,  3.0000,  6.0000,  0.0000,  0.0000,  0.0000,
           3.0000],
         [ 1.0000, 56.0000,  1.0000,  5.0000,  4.0000,  1.0000,  0.0000,  2.0000,
           3.0000]]),
 tensor([3, 0, 1, 1, 0]))

In [ ]:
from torch.utils.data import DataLoader

BATCH_SIZE = 16
train_dataloader = DataLoader(dataset=train_dataset,
                              batch_size=BATCH_SIZE,
                              shuffle=True)
test_dataloader = DataLoader(dataset=test_dataset,
                             batch_size=BATCH_SIZE,
                             shuffle=False)
train_dataloader, test_dataloader


(<torch.utils.data.dataloader.DataLoader at 0x7daf1091fd90>,
 <torch.utils.data.dataloader.DataLoader at 0x7daf1091f130>)

In [ ]:
next(iter(train_dataloader))

[tensor([[ 0.0000, 38.0000,  1.0000,  7.0000,  4.0000,  1.0000,  5.0000,  0.0000,
           1.0000],
         [ 1.0000, 49.0000,  1.0000,  3.0000,  4.0000,  1.0000,  2.6417,  1.0000,
           2.0000],
         [ 0.0000, 37.0000,  1.0000,  7.0000,  0.0000,  1.0000,  0.0000,  0.0000,
           0.0000],
         [ 0.0000, 73.0000,  1.0000,  2.0000,  4.0000,  1.0000,  1.0000,  0.0000,
           1.0000],
         [ 0.0000, 40.0000,  0.0000,  2.0000,  1.0000,  0.0000,  1.0000,  0.0000,
           1.0000],
         [ 1.0000, 32.0000,  0.0000,  4.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           1.0000],
         [ 0.0000, 22.0000,  0.0000,  3.0000,  0.0000,  0.0000,  2.6417,  0.0000,
           2.0000],
         [ 1.0000, 71.0000,  1.0000,  1.0000,  2.0000,  1.0000,  1.0000,  0.0000,
           3.0000],
         [ 0.0000, 37.0000,  1.0000,  3.0000,  1.0000,  1.0000,  1.0000,  1.0000,
           3.0000],
         [ 1.0000, 25.0000,  1.0000,  2.0000,  3.0000,  1.0000,  0.0000,  1.0000,


In [ ]:
from torch import nn

class ModelV0(nn.Module):
  def __init__(self,
               input_shape: int,
               hidden_layers: int,
               output_shape: int = 4):
    super().__init__()
    self.layer_stack = nn.Sequential(
        nn.Linear(in_features=input_shape,
                  out_features=hidden_layers),
        nn.ReLU(),
        nn.Linear(in_features=hidden_layers,
                  out_features=hidden_layers),
        # nn.ReLU(),
        # nn.Linear(in_features=hidden_layers,
        #           out_features=hidden_layers),
        nn.ReLU(),
        nn.Linear(in_features=hidden_layers,
                  out_features=output_shape)
    )

  def forward(self, x):
    return self.layer_stack(x)


In [ ]:
model_0 = ModelV0(input_shape=X.shape[1], hidden_layers=30, output_shape=4)
model_0

ModelV0(
  (layer_stack): Sequential(
    (0): Linear(in_features=9, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=30, bias=True)
    (3): ReLU()
    (4): Linear(in_features=30, out_features=4, bias=True)
  )
)

In [ ]:
model_0.state_dict().keys()

odict_keys(['layer_stack.0.weight', 'layer_stack.0.bias', 'layer_stack.2.weight', 'layer_stack.2.bias', 'layer_stack.4.weight', 'layer_stack.4.bias'])

In [ ]:
def train_step(model: torch.nn.Module,
               dataloader: torch.utils.data.DataLoader,
               loss_fn: torch.nn.Module,
               optimizer: torch.optim.Optimizer,
               device=device):
  net_loss, net_acc = 0, 0
  model.train()
  for batch, (X, y) in enumerate(dataloader):
    X, y = X.to(device), y.to(device)
    y_pred = model(X)
    loss = loss_fn(y_pred, y)
    net_loss += loss
    net_acc += (y_pred.argmax(dim=1) == y).sum().item() / len(y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
  net_loss /= len(dataloader)
  net_acc /= len(dataloader)
  return net_loss, net_acc

In [ ]:
def test_step(model: torch.nn.Module,
              dataloader: torch.utils.data.DataLoader,
              loss_fn: torch.nn.Module,
              device=device):
  net_loss, net_acc = 0, 0
  model.eval()
  with torch.inference_mode():
    for batch, (X, y) in enumerate(dataloader):
      X, y = X.to(device), y.to(device)
      y_pred = model(X)
      net_loss += loss_fn(y_pred, y)
      net_acc += (y_pred.argmax(dim=1) == y).sum().item() / len(y)
    net_loss = net_loss / len(dataloader)
    net_acc = net_acc / len(dataloader)
    return net_loss, net_acc

In [ ]:
from tqdm.auto import tqdm

def train(model: torch.nn.Module,
          train_dataloader: torch.utils.data.DataLoader,
          test_dataloader: torch.utils.data.DataLoader,
          optimizer: torch.optim.Optimizer,
          loss_fn: torch.nn.Module,
          epochs: int = 5,
          device = device):

  results = {"train_loss": [],
             "train_acc": [],
             "test_loss": [],
             "test_acc": []}
  for epoch in range(epochs):
    train_loss, train_acc = train_step(model=model,
                                      dataloader=train_dataloader,
                                      loss_fn=loss_fn,
                                      optimizer=optimizer,
                                      device=device)
    test_loss, test_acc = test_step(model=model,
                                    dataloader=test_dataloader,
                                    loss_fn=loss_fn,
                                    device=device)

    print(f"Epoch: {epoch} | Train loss: {train_loss:.4f} | Train acc: {train_acc:.4f} | Test loss: {test_loss:4f} | Test acc: {test_acc:.4f}")
    results["train_loss"].append(train_loss)
    results["train_acc"].append(train_acc)
    results["test_loss"].append(test_loss)
    results["test_acc"].append(test_acc)

  return results

In [ ]:
NUM_EPOCHS = 50

model_0 = ModelV0(input_shape=X.shape[1],
                  hidden_layers=100,
                  output_shape=4)

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_0.parameters(), lr=0.001)



In [ ]:
results = train(model=model_0,
                train_dataloader=train_dataloader,
                test_dataloader=test_dataloader,
                optimizer=optimizer,
                loss_fn=loss_fn,
                epochs=NUM_EPOCHS)


Epoch: 0 | Train loss: 1.2983 | Train acc: 0.3955 | Test loss: 1.200278 | Test acc: 0.4631
Epoch: 1 | Train loss: 1.2093 | Train acc: 0.4471 | Test loss: 1.166892 | Test acc: 0.4566
Epoch: 2 | Train loss: 1.1818 | Train acc: 0.4632 | Test loss: 1.176330 | Test acc: 0.4762
Epoch: 3 | Train loss: 1.1658 | Train acc: 0.4757 | Test loss: 1.146599 | Test acc: 0.4965
Epoch: 4 | Train loss: 1.1529 | Train acc: 0.4751 | Test loss: 1.130464 | Test acc: 0.4953
Epoch: 5 | Train loss: 1.1470 | Train acc: 0.4823 | Test loss: 1.223822 | Test acc: 0.4667
Epoch: 6 | Train loss: 1.1353 | Train acc: 0.4861 | Test loss: 1.126122 | Test acc: 0.5103
Epoch: 7 | Train loss: 1.1289 | Train acc: 0.4908 | Test loss: 1.145486 | Test acc: 0.4769
Epoch: 8 | Train loss: 1.1207 | Train acc: 0.4999 | Test loss: 1.113992 | Test acc: 0.4916
Epoch: 9 | Train loss: 1.1129 | Train acc: 0.4978 | Test loss: 1.118535 | Test acc: 0.5103
Epoch: 10 | Train loss: 1.1104 | Train acc: 0.4975 | Test loss: 1.128150 | Test acc: 0.494

In [ ]:
model_0(X_test[0])

tensor([ 1.0740, -1.0205, -1.1829,  0.9279], grad_fn=<ViewBackward0>)

In [ ]:
y_pred = model_0(X_test).argmax(dim=1)
y_pred

tensor([0, 0, 3, 2, 3, 2, 2, 1, 3, 0, 1, 3, 3, 3, 3, 0, 2, 2, 0, 3, 3, 0, 3, 3,
        0, 0, 2, 3, 2, 2, 2, 0, 2, 2, 3, 3, 3, 0, 0, 2, 2, 1, 3, 3, 2, 3, 3, 1,
        2, 2, 2, 2, 0, 0, 3, 1, 3, 3, 3, 3, 0, 1, 3, 3, 2, 2, 3, 3, 0, 0, 2, 3,
        0, 1, 1, 0, 3, 2, 3, 2, 0, 3, 2, 1, 3, 0, 0, 1, 0, 1, 3, 3, 1, 2, 1, 0,
        3, 1, 0, 0, 3, 3, 1, 3, 0, 3, 3, 2, 3, 0, 2, 0, 1, 3, 0, 2, 0, 1, 2, 0,
        0, 1, 0, 0, 3, 1, 0, 0, 0, 3, 3, 0, 3, 3, 0, 3, 2, 0, 3, 3, 0, 0, 1, 0,
        2, 2, 3, 2, 0, 3, 0, 2, 3, 2, 3, 3, 3, 3, 2, 0, 3, 2, 2, 2, 0, 3, 2, 3,
        2, 1, 0, 0, 2, 0, 0, 3, 2, 3, 1, 2, 2, 1, 0, 2, 2, 3, 0, 0, 1, 3, 3, 3,
        1, 2, 3, 2, 0, 2, 3, 0, 3, 3, 2, 0, 3, 0, 2, 1, 3, 0, 0, 3, 3, 3, 0, 3,
        0, 3, 3, 3, 2, 0, 2, 2, 0, 3, 1, 0, 0, 3, 1, 2, 3, 0, 3, 2, 1, 1, 3, 3,
        3, 2, 2, 2, 0, 3, 3, 0, 0, 2, 2, 3, 3, 3, 2, 3, 1, 1, 2, 3, 0, 2, 0, 3,
        0, 1, 0, 1, 0, 1, 3, 2, 2, 3, 0, 3, 2, 2, 1, 2, 0, 3, 2, 0, 3, 2, 2, 1,
        3, 2, 1, 2, 3, 3, 3, 0, 2, 2, 0,

In [ ]:
from sklearn import tree

clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)


0.4349442379182156

In [ ]:
clf.predict(X_test[4].unsqueeze(dim=0))

array([3])

In [ ]:
y_test[4]

tensor(3)

In [ ]:
for i in range(10):
  print(f"Predicted: {clf.predict(X_test[i].unsqueeze(dim=0)).item()} | Actual: {y_test[i]}")

Predicted: 3 | Actual: 3
Predicted: 0 | Actual: 0
Predicted: 3 | Actual: 3
Predicted: 1 | Actual: 2
Predicted: 3 | Actual: 3
Predicted: 1 | Actual: 2
Predicted: 0 | Actual: 1
Predicted: 1 | Actual: 0
Predicted: 3 | Actual: 3
Predicted: 0 | Actual: 2


In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'max_depth': [None, 10, 20, 30, 40, 50],
    'min_samples_split': [2, 10, 20],
    'min_samples_leaf': [1, 5, 10],
    'max_features': [None, 'sqrt', 'log2']
}
grid_search = GridSearchCV(estimator=tree.DecisionTreeClassifier(), param_grid=param_grid, cv=5, n_jobs=-1)
grid_search.fit(X_train, y_train)
print(f"Best parameters found: {grid_search.best_params_}")
best_model = grid_search.best_estimator_
best_model.score(X_test, y_test)

Best parameters found: {'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 10, 'min_samples_split': 2}


0.4919454770755886

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clf.fit(X_train, y_train)
rf_clf.score(X_test, y_test)

0.46964064436183395

In [ ]:
from sklearn.model_selection import cross_val_score

cross_val_scores = cross_val_score(tree.DecisionTreeClassifier(), X_train, y_train, cv=5)
print(f"Cross-validation scores: {cross_val_scores}")
print(f"Average cross-validation score: {cross_val_scores.mean()}")

Cross-validation scores: [0.44803854 0.44008264 0.44214876 0.43801653 0.42768595]
Average cross-validation score: 0.43919448504945596


In [ ]:
clf = tree.DecisionTreeClassifier(class_weight='balanced')
clf.fit(X_train, y_train)
clf.score(X_test, y_test)


0.43370508054522927

In [ ]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.4510532837670384

In [ ]:
from sklearn import svm

model_rbf = svm.SVC(degree=3, gamma="scale", kernel="rbf")
model_rbf.fit(X_train, y_train)
model_rbf.score(X_test, y_test)

0.45724907063197023

## Make predictions


In [ ]:
df1 = pd.read_csv("Consumer_Test_Dataset.csv")
df2 = df1.copy()
df1.head(5)

Unnamed: 0  Gender  Age Ever_Married  Family_Size  Profession Graduated  \
0           0  Female   36          Yes          1.0    Engineer       Yes   
1           1    Male   37          Yes          4.0  Healthcare       Yes   
2           2  Female   69          Yes          1.0         NaN        No   
3           3    Male   59          Yes          2.0   Executive        No   
4           4  Female   19           No          4.0   Marketing        No   

   Work_Experience Energy_Consumption Preferred_Renewable  
0              0.0                Low               Solar  
1              8.0            Average               Solar  
2              0.0                Low               Solar  
3             11.0               High               Solar  
4              NaN                Low               Solar

In [ ]:
len(df1)

2627

In [ ]:
df1 = df1.replace(to_replace="Male", value=0)
df1 = df1.replace(to_replace="Female", value=1)
df1 = df1.replace(to_replace="Yes", value=1)
df1 = df1.replace(to_replace="No", value=0)
df1['Work_Experience'] = df1['Work_Experience'].fillna(avg_work_experience)
df1 = df1.replace(to_replace="Low", value=0)
df1 = df1.replace(to_replace="Average", value=1)
df1 = df1.replace(to_replace="High", value=2)
df1['Family_Size'] = df1['Family_Size'].fillna(avg_family_size)

df1 = df1.replace(to_replace="A", value=0)
df1 = df1.replace(to_replace="B", value=1)
df1 = df1.replace(to_replace="C", value=2)
df1 = df1.replace(to_replace="D", value=3)
df1

Unnamed: 0  Gender  Age  Ever_Married  Family_Size     Profession  \
0              0       1   36           1.0          1.0       Engineer   
1              1       0   37           1.0          4.0     Healthcare   
2              2       1   69           1.0          1.0            NaN   
3              3       0   59           1.0          2.0      Executive   
4              4       1   19           0.0          4.0      Marketing   
...          ...     ...  ...           ...          ...            ...   
2622        2622       0   29           0.0          4.0     Healthcare   
2623        2623       1   35           0.0          1.0         Doctor   
2624        2624       1   53           0.0          2.0  Entertainment   
2625        2625       0   47           1.0          5.0      Executive   
2626        2626       1   43           0.0          3.0     Healthcare   

      Graduated  Work_Experience  Energy_Consumption Preferred_Renewable  
0           1.0         0.000000                   0               Solar  
1           1.0         8.000000                   1               Solar  
2           0.0         0.000000                   0               Solar  
3           0.0        11.000000                   2               Solar  
4           0.0         2.641663                   0               Solar  
...         ...              ...                 ...                 ...  
2622        0.0         9.000000                   0               Solar  
2623        1.0         1.000000                   0               Solar  
2624        1.0         2.641663                   0               Solar  
2625        1.0         1.000000                   2               Hydro  
2626        1.0         9.000000                   0      Not Interested  

[2627 rows x 10 columns]

In [ ]:
for i, source in enumerate(professions):
  df1['Profession'][df1['Profession'] == source] = i
avg_profession = df1['Profession'].mean()
df1['Profession'] = df1['Profession'].fillna(avg_profession)
avg_profession

<ipython-input-53-e4db59ec5021>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Profession'][df1['Profession'] == source] = i
<ipython-input-53-e4db59ec5021>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Profession'][df1['Profession'] == source] = i
<ipython-input-53-e4db59ec5021>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Profession'][df1['Profession'] == source] = i
<ipython-input-53-e4db59ec5021>:2: SettingW

3.3151796060254926

In [ ]:
avg_married = df1['Ever_Married'].mean()
df1['Ever_Married'] = df1['Ever_Married'].fillna(avg_married)
avg_married

0.5898331393092744

In [ ]:
for i, source in enumerate(renewable):
  df1['Preferred_Renewable'][df1['Preferred_Renewable'] == source] = i
avg_preferred_renewable = df1['Preferred_Renewable'].mean()
df1['Preferred_Renewable'] = df1['Preferred_Renewable'].fillna(avg_preferred_renewable)
avg_preferred_renewable

<ipython-input-55-880a2e04fb0b>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Preferred_Renewable'][df1['Preferred_Renewable'] == source] = i
<ipython-input-55-880a2e04fb0b>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Preferred_Renewable'][df1['Preferred_Renewable'] == source] = i
<ipython-input-55-880a2e04fb0b>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Preferred_Renewable'][df1['Preferred_Renewable'] == s

1.40616570327553

In [ ]:
avg_graduated = df1['Graduated'].mean()
df1['Graduated'] = df1['Graduated'].fillna(avg_graduated)
avg_graduated

0.6154437187860161

In [ ]:
df1['Preferred_Renewable'].isnull().values.any()


False

In [ ]:
df1 = df1.drop('Unnamed: 0', axis=1)
df1.head(5)

Gender  Age  Ever_Married  Family_Size  Profession  Graduated  \
0       1   36           1.0          1.0     1.00000        1.0   
1       0   37           1.0          4.0     0.00000        1.0   
2       1   69           1.0          1.0     3.31518        0.0   
3       0   59           1.0          2.0     5.00000        0.0   
4       1   19           0.0          4.0     8.00000        0.0   

   Work_Experience  Energy_Consumption  Preferred_Renewable  
0         0.000000                   0                  1.0  
1         8.000000                   1                  1.0  
2         0.000000                   0                  1.0  
3        11.000000                   2                  1.0  
4         2.641663                   0                  1.0

In [ ]:
data1 = df1.to_numpy()
data1[:5]

array([[ 1.        , 36.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  1.        ],
       [ 0.        , 37.        ,  1.        ,  4.        ,  0.        ,
         1.        ,  8.        ,  1.        ,  1.        ],
       [ 1.        , 69.        ,  1.        ,  1.        ,  3.31517961,
         0.        ,  0.        ,  0.        ,  1.        ],
       [ 0.        , 59.        ,  1.        ,  2.        ,  5.        ,
         0.        , 11.        ,  2.        ,  1.        ],
       [ 1.        , 19.        ,  0.        ,  4.        ,  8.        ,
         0.        ,  2.64166321,  0.        ,  1.        ]])

In [ ]:
data1.shape

(2627, 9)

In [ ]:
X1 = data1[:, 0:9]
X1.shape

(2627, 9)

In [ ]:
X1

array([[ 1.        , 36.        ,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 0.        , 37.        ,  1.        , ...,  8.        ,
         1.        ,  1.        ],
       [ 1.        , 69.        ,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [ 1.        , 53.        ,  0.        , ...,  2.64166321,
         0.        ,  1.        ],
       [ 0.        , 47.        ,  1.        , ...,  1.        ,
         2.        ,  0.        ],
       [ 1.        , 43.        ,  0.        , ...,  9.        ,
         0.        ,  2.        ]])

In [ ]:
X1 = torch.from_numpy(X1)
X1.shape

torch.Size([2627, 9])

In [ ]:
X1 = X1.type(torch.float32)

In [ ]:
predictions = model_0(X1).argmax(dim=1).tolist()
predictions[:10]

[0, 3, 0, 2, 2, 1, 1, 2, 2, 3]

In [ ]:
for i, prediction in enumerate(predictions):
  if prediction == 0:
    predictions[i] = 'A'
  elif prediction == 1:
    predictions[i] = 'B'
  elif prediction == 2:
    predictions[i] = 'C'
  elif prediction == 3:
    predictions[i] = 'D'
  else:
    predictions[i] = 'Error'
predictions[:5]

['A', 'D', 'A', 'C', 'C']

In [ ]:
len(predictions)

2627

In [ ]:
df2.head(5)

Unnamed: 0  Gender  Age Ever_Married  Family_Size  Profession Graduated  \
0           0  Female   36          Yes          1.0    Engineer       Yes   
1           1    Male   37          Yes          4.0  Healthcare       Yes   
2           2  Female   69          Yes          1.0         NaN        No   
3           3    Male   59          Yes          2.0   Executive        No   
4           4  Female   19           No          4.0   Marketing        No   

   Work_Experience Energy_Consumption Preferred_Renewable  
0              0.0                Low               Solar  
1              8.0            Average               Solar  
2              0.0                Low               Solar  
3             11.0               High               Solar  
4              NaN                Low               Solar

In [ ]:
df2['Group'] = predictions
df2.head(5)

Unnamed: 0  Gender  Age Ever_Married  Family_Size  Profession Graduated  \
0           0  Female   36          Yes          1.0    Engineer       Yes   
1           1    Male   37          Yes          4.0  Healthcare       Yes   
2           2  Female   69          Yes          1.0         NaN        No   
3           3    Male   59          Yes          2.0   Executive        No   
4           4  Female   19           No          4.0   Marketing        No   

   Work_Experience Energy_Consumption Preferred_Renewable Group  
0              0.0                Low               Solar     A  
1              8.0            Average               Solar     D  
2              0.0                Low               Solar     A  
3             11.0               High               Solar     C  
4              NaN                Low               Solar     C

In [ ]:
with open("Edited_Consumer_Test_Dataset.csv", "wb") as f:
  f.write(df2.to_csv(index=False).encode("utf-8"))
  print("csv file created")

csv file created


### Q4: In the above case your team already had data from which customers were classified in groups. How will you predict the classes if the groups and it’s data weren’t available? State the method you would have used.

Instead of deploying a Deep Learning model which predicts the group for the customers, I would try to find some pattern among the customers and using that write code to distribute them in the four classes